const Categories = [
  {
    id: 1,
    title: "Jonas Bjorgen",
    price: "£55",
    image: require("./face.jpg"),
    description: "MSc accounting and finance",
    category: "Accounting",
  },
  {
    id: 2,
    title: "Kim Bauer",
    price: "£75",
    image: require("./face2.jpg"),
    description: "PhD Arts",
    category: "Arts",
  },
  {
    id: 3,
    title: "Matt Moorawecki",
    price: "£110",
    image: require("./face.jpg"),
    description: "PhD Politics",
    category: "Politics",
  },
  {
    id: 4,
    title: "Alan Doe",
    price: "£75",
    image: require("./face.jpg"),
    description: "PhD Geopolitics",
    category: "Politics",
  },
  {
    id: 5,
    title: "Christian Paul",
    price: "£80",
    image: require("./face.jpg"),
    description: "MSc Cybersecurity",
    category: "Computing",
  },
  {
    id: 6,
    title: "Anton Mriya",
    price: "£65",
    image: require("./face.jpg"),
    description: "MSc Graphic Design",
    category: "Computing",
  },
  {
    id: 7,
    title: "Maria Sparrow",
    price: "£85",
    image: require("./face.jpg"),
    description: "Business Owner",
    category: "Accounting",
  },
  {
    id: 8,
    title: "Maria Magdalena",
    price: "£65",
    image: require("./face.jpg"),
    description: "MSc Dietitian",
    category: "Biology",
  },
  {
    id: 9,
    title: "Maria Magdalena",
    price: "£30",
    image: require("./face.jpg"),
    description: "MSc Business Management",
    category: "Business",
  },
  {
    id: 10,
    title: "Dr Adrian Hopkins",
    price: "£80",
    image: require("./face.jpg"),
    description: "PhD Accounting and finance",
    category: "Accounting",
  },
  {
    id: 11,
    title: "Kuebo Nafide",
    price: "£40",
    image: require("./face.jpg"),
    description: "BSc Digital design",
    category: "Arts",
  },
  {
    id: 12,
    title: "Jako Tacco",
    price: "£65",
    image: require("./face.jpg"),
    description: "MSc Arts History",
    category: "Arts",
  },
  {
    id: 13,
    title: "Adrian Dudu",
    price: "£50",
    image: require("./dudu.jpg"),
    description: "PhD Politics",
    category: "Politics",
  },
  {
    id: 14,
    title: "Jhiki Drener",
    price: "£20",
    image: require("./face.jpg"),
    description: "Personal Trainer",
    category: "Biology",
  },
  {
    id: 15,
    title: "Michael Jaglak",
    price: "£70",
    image: require("./face.jpg"),
    description: "PhD Nutrition",
    category: "Biology",
  },
  {
    id: 16,
    title: "Rich Peja",
    price: "£70",
    image: require("./face.jpg"),
    description: "Businessman",
    category: "Business",
  },
  {
    id: 17,
    title: "Jacek Graniecki",
    price: "£75",
    image: require("./face.jpg"),
    description: "Keptn",
    category: "Business",
  },
  {
    id: 18,
    title: "Edward Homonto",
    price: "£75",
    image: require("./face.jpg"),
    description: "Senior software engineer",
    category: "Computing",
  },
  {
    id: 19,
    title: "Dr Nio Wuwu",
    price: "£30",
    image: require("./face.jpg"),
    description: "PhD Chemistry",
    category: "Chemistry",
  },
  {
    id: 20,
    title: "Dr Luiza Palhais",
    price: "£45",
    image: require("./face.jpg"),
    description: "PhD Chemistry",
    category: "Chemistry",
  },
  {
    id: 21,
    title: "Janchar Makamere",
    price: "£40",
    image: require("./face.jpg"),
    description: "MSc Chemistry",
    category: "Chemistry",
  },
  {
    id: 22,
    title: "Jack Sasin",
    price: "£70",
    image: require("./face.jpg"),
    description: "MSc National Economy",
    category: "Maths",
  },
  {
    id: 23,
    title: "Adam Glapincky",
    price: "£30",
    image: require("./face.jpg"),
    description: "Bank Director",
    category: "Maths",
  },
  {
    id: 24,
    title: "Edmund Crawl",
    price: "£50",
    image: require("./face.jpg"),
    description: "Mathematician",
    category: "Maths",
  },
  {
    id: 25,
    title: "Piotr Ipawel",
    price: "£35",
    image: require("./face.jpg"),
    description: "Physician",
    category: "Physics",
  },
  {
    id: 26,
    title: "Pigey Kukulski",
    price: "£65",
    image: require("./face.jpg"),
    description: "MSc Physics",
    category: "Physics",
  },
  {
    id: 27,
    title: "Dr Elisabeth Zalewska",
    price: "£80",
    image: require("./face.jpg"),
    description: "PhD Physics",
    category: "Physics",
  },
  {
    id: 28,
    title: "Dr Zbigniew Freud",
    price: "£80",
    image: require("./face.jpg"),
    description: "PhD Psychology",
    category: "Psychology",
  },
  {
    id: 29,
    title: "Maja Stazko",
    price: "£40",
    image: require("./face.jpg"),
    description: "Mental health specialist",
    category: "Psychology",
  },
  {
    id: 30,
    title: "Prof Alan Wake",
    price: "£100",
    image: require("./face.jpg"),
    description: "PhD Criminal Behaviour",
    category: "Psychology",
  },
  {
    id: 31,
    title: "Anthony McCherry-Witch",
    price: "£30",
    image: require("./face.jpg"),
    description: "BSc Sociology",
    category: "Sociology",
  },
  {
    id: 32,
    title: "Al Bundy",
    price: "£70",
    image: require("./face.jpg"),
    description: "PhD Sociology",
    category: "Sociology",
  },
  {
    id: 33,
    title: "Romuald Tolkien",
    price: "£45",
    image: require("./face.jpg"),
    description: "MSc Sociology",
    category: "Sociology",
  },
];

export default Categories;
